language: scala
scala:
  - 2.11.11
jdk:
  - oraclejdk7
  - openjdk6
cache:
  directories:
  - $HOME/.ivy2
before_cache:
  - find $HOME/.ivy2 -type f -name "ivydata-*.properties"
  - find $HOME/.ivy2 -type f -name "ivydata-*.properties" -delete
  - find $HOME/.ivy2 -type f -name "ivydata-*.properties"
